### ISSUE TITLE
go get failing

### ISSUE THREAD

**Issue by eolexe** [emiddleton/gads#1]
Hi, I am looking forward in getting your lib working for myself and contribute. 
When I tried: go get github.com/emiddleton/gads

I got following issue
..GOPATH../src/github.com/emiddleton/gads/oauth2.go:17: undefined: oauth2.Context

**Comment by emiddleton** [comment]
Thanks for reporting this.  This should fix the problem 4df49a74741469fc9f2dc9c71f6d7985824527dd

**Comment by eolexe** [comment]
Works!
